name: build-and-test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cppstd: [11, 14, 17, 20]
    steps:
      - uses: actions/checkout@v2
      - name: install-build-tools
        run: |
          sudo apt-get install -y gcc g++ cmake make libboost-all-dev
      - name: build
        run: |
          cmake -D CMAKE_CXX_STANDARD=${{ matrix.cppstd }} .
          make
      - name: unit-tests
        run: |
          ./tests/unit_tests
      - name: run-examples
        run: |
          export EXAMPLES=(
            x01_hello_world
            x02_ordered_children
            )
          for x in ${EXAMPLES[*]}; do
            echo ===
            ./examples/$x
          done
